[ALPS02227655] sched: fix build warning
[Detail]
Fix build warning
1. @kernel/sched/fair.c:2537:3: error: format %lu expects argument
of type long unsigned int, but argument 10 has type u32
[-Werror=format=]
   mt_sched_printf(sched_lb_info,
   ^
2. @kernel/sched/fair.c:7644:2: error: format %lu expects argument
of type long unsigned int, but argument 7 has type unsigned int
[-Werror=format=]
  mt_sched_printf(sched_lb_info, "[%s] cpu=0x%lx no_capacity=%d
  ^
weight=%lu nr=%d type=%d, usage=%lu",

3. @kernel/sched/fair.c:4768:19: error: hmp_cpu_mask_setup defined
but not used [-Werror=unused-function]
 static int __init hmp_cpu_mask_setup(void) { return 1; }
                   ^
[Solution]
Fix build warning

[Feature] System Performance

MTK-Commit-Id: 1766417c50bf6f8b3f318d6063ab265a510656dd

Change-Id: I9db6f00304b249378c350a018e50fbb9dfeb2b57
Signed-off-by: Mandy Liu <mandyjh.liu@mediatek.com>
CR-Id: ALPS02227655