[ALPS02212337] PTP-OD: revert "add PTP-OD driver for mt8173"
[Detail]
The following projects cannot be built successfully
because of this patch. Therefore, I revert this patch.

1. tb8176evb_64-eng
2. tb8176p1_2k_64-user
3. tb8176p1_64_trusty-eng

ERROR File:android(14939) ERROR:2
"kernel-3.18/drivers/misc/mediatek/base/power/mt8173/mt_ptp.c#1b699c6"
[Changelist:1b699c6]
Check in time:2015-09-02 20:49:52 +0800
[ERROR Log:]
[line:2540]: undefined reference to `mt_fh_popod_save;
[line:2609]: undefined reference to `mt_fh_popod_restore;

[Solution]
revert commit 369033f6e96bfd880d8172a5cb2bc484b8478ed0 ("[ALPS02212337] PTP-OD: add PTP-OD driver for mt8173")

[Feature] PTP-OD (Performance Thermal Power-Over Drive)

MTK-Commit-Id: bd49cd1e486685033aca17b4a6a7e73ddd4a044a

Change-Id: Ifa50576df8fd1f3c6ea7031bd3726e0da07c2b0f
CR-Id: ALPS02212337
Signed-off-by: Roger Lu <roger.lu@mediatek.com>